services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: nestjs-app-prod
    ports:
      - "443:443"
    env_file:
      - .env
    environment:
      NODE_ENV: PRODUCTION
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16.4
    container_name: whiteboard-postgres-prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata-prod:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0
    container_name: whiteboard-redis-prod
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redisdata-prod:/data