services:
  postgres:
    image: postgres:16.4
    container_name: whiteboard-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./nest-server/pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0
    container_name: whiteboard-redis
    restart: always
    ports:
      - "6379:6379"
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - ./nest-server/redisdata:/var/lib/redis/data

  nest-server:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: whiteboard-nest-server
    ports:
      - "443:443"
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production