services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs-app-dev
    volumes:
      - .:/workspace:cached
    command: npm run start:dev
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: DEVELOPMENT
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16.4
    container_name: whiteboard-postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata-dev:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0
    container_name: whiteboard-redis-dev
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redisdata-dev:/data